name: IA News Agent (Email Only)

on:
  schedule:
    # 07:50 Europe/Rome -> 05:50 UTC in ora legale (aprile-ottobre)
    - cron: "50 5 * 4-10 *"
    # 07:50 Europe/Rome -> 06:50 UTC in ora solare (gennaio-marzo e novembre-dicembre)
    - cron: "50 6 * 1-3,11-12 *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4 requests
      - name: Run agent (email only)
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python ia_news_email_only.py
      - name: Persist state
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add seen.json last_sent.json || true
          git commit -m "Update state" || echo "Nothing to commit"
          git push
